name: Deployment

on:
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Deploy the api to the dav Backend
      uses: dav-apps/dav-api-deployment-action@master
      with:
        base-url: ${{ secrets.API_BASE_URL }}
        api-id: ${{ secrets.API_ID }}
        auth: ${{ secrets.AUTH }}